# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_code',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_header',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output_case',
        ),
    ]
